global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'qflow-cluster'
    environment: 'production'

rule_files:
  - "qflow_rules.yml"
  - "ecosystem_rules.yml"

scrape_configs:
  # Qflow main service
  - job_name: 'qflow'
    static_configs:
      - targets: ['qflow:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Qflow API metrics
  - job_name: 'qflow-api'
    static_configs:
      - targets: ['qflow:8080']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # IPFS metrics
  - job_name: 'ipfs'
    static_configs:
      - targets: ['ipfs:5001']
    metrics_path: '/debug/metrics/prometheus'
    scrape_interval: 60s
    scrape_timeout: 15s

  # Node exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor (if available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true