version: '3.8'

services:
  squid:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - SQUID_PORT=3001
      - SQUID_HOST=0.0.0.0
      - SQUID_MOCK_MODE=true
      - EVENT_BUS_URL=redis://redis:6379
      - SQUID_DB_URL=mongodb://mongo:27017/squid
    depends_on:
      - redis
      - mongo
    volumes:
      - ./src:/app/src
      - ./contracts:/app/contracts
      - ./events:/app/events
    command: npm run dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=squid
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data: