apiVersion: v1
kind: ConfigMap
metadata:
  name: qflow-config
  namespace: qflow
  labels:
    app.kubernetes.io/name: qflow
    app.kubernetes.io/component: config
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  QFLOW_PORT: "8080"
  QFLOW_WEBSOCKET_PORT: "9090"
  QFLOW_LIBP2P_PORT: "4001"
  QFLOW_DATA_DIR: "/app/data"
  QFLOW_ENABLE_METRICS: "true"
  QFLOW_ENABLE_TRACING: "true"
  QFLOW_MAX_CONCURRENT_FLOWS: "500"
  QFLOW_VALIDATION_TIMEOUT: "5000"
  QFLOW_SANDBOX_MEMORY_LIMIT: "128"
  QFLOW_SANDBOX_TIMEOUT: "30000"
  QFLOW_VALIDATION_CACHE_TTL: "3600"
  QFLOW_PERFORMANCE_MONITORING: "true"
  IPFS_API_URL: "http://qflow-ipfs:5001"
  REDIS_URL: "redis://qflow-redis:6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qflow-monitoring-config
  namespace: qflow
  labels:
    app.kubernetes.io/name: qflow
    app.kubernetes.io/component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "qflow_rules.yml"
    
    scrape_configs:
      - job_name: 'qflow'
        static_configs:
          - targets: ['qflow-service:9090']
        metrics_path: '/metrics'
        scrape_interval: 10s
      
      - job_name: 'qflow-api'
        static_configs:
          - targets: ['qflow-service:8080']
        metrics_path: '/api/v1/metrics'
        scrape_interval: 30s
      
      - job_name: 'redis'
        static_configs:
          - targets: ['qflow-redis:6379']
      
      - job_name: 'ipfs'
        static_configs:
          - targets: ['qflow-ipfs:5001']
        metrics_path: '/debug/metrics/prometheus'
  
  qflow_rules.yml: |
    groups:
      - name: qflow.rules
        rules:
          - alert: QflowHighErrorRate
            expr: rate(qflow_errors_total[5m]) > 0.1
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High error rate in Qflow"
              description: "Qflow error rate is {{ $value }} errors per second"
          
          - alert: QflowHighLatency
            expr: histogram_quantile(0.95, rate(qflow_request_duration_seconds_bucket[5m])) > 1
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High latency in Qflow"
              description: "95th percentile latency is {{ $value }} seconds"
          
          - alert: QflowServiceDown
            expr: up{job="qflow"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Qflow service is down"
              description: "Qflow service has been down for more than 1 minute"