apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: qflow
  namespace: qflow

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- rbac.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- ipfs-deployment.yaml
- redis-deployment.yaml
- monitoring.yaml
- hpa.yaml
- pdb.yaml
- network-policy.yaml

images:
- name: qflow
  newTag: latest

commonLabels:
  app.kubernetes.io/part-of: anarq-ecosystem
  app.kubernetes.io/managed-by: kustomize

namespace: qflow

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: qflow
  spec:
    template:
      metadata:
        annotations:
          config/checksum: ${CONFIG_CHECKSUM}
          secret/checksum: ${SECRET_CHECKSUM}

configMapGenerator:
- name: qflow-version
  literals:
  - version=${VERSION}
  - build=${BUILD_NUMBER}
  - commit=${GIT_COMMIT}

secretGenerator:
- name: qflow-runtime-secrets
  type: Opaque
  literals:
  - runtime-token=${RUNTIME_TOKEN}

generatorOptions:
  disableNameSuffixHash: true