apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qflow-data
  namespace: qflow
  labels:
    app.kubernetes.io/name: qflow
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd  # Adjust based on your cluster's storage classes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qflow-ipfs-data
  namespace: qflow
  labels:
    app.kubernetes.io/name: qflow-ipfs
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qflow-redis-data
  namespace: qflow
  labels:
    app.kubernetes.io/name: qflow-redis
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd