apiVersion: v1
kind: ServiceAccount
metadata:
  name: qflow
  namespace: qflow
  labels:
    app.kubernetes.io/name: qflow
    app.kubernetes.io/component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qflow
  namespace: qflow
  labels:
    app.kubernetes.io/name: qflow
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qflow
  namespace: qflow
  labels:
    app.kubernetes.io/name: qflow
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: qflow
  namespace: qflow
roleRef:
  kind: Role
  name: qflow
  apiGroup: rbac.authorization.k8s.io